version: '3.9'

services:
  colyseus:
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - port=3000
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.25.2-alpine
    depends_on:
      - colyseus
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "46600:80"